[package]
name    = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
agents     = { workspace = true }
domain     = { workspace = true }
ict        = { workspace = true }
mt5-client = { workspace = true }
risk       = { workspace = true }
thiserror  = { workspace = true }
tokio      = { workspace = true }
tracing    = { workspace = true }
